[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
#secret_key = "aabb"
limits = { forms = 32768 }
template_dir = "_templates/"



[production]
address = "0.0.0.0"
port = 8000
workers = 8
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
#secret_key = "aabb"
limits = { forms = 32768 }
template_dir = "_templates/"